### ISSUE TITLE
Incidencia - EDA - Error al mostrar nombre de columna en tablas cruzadas. 

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#100]
**Descripción**
Para generar una tabla cruzada, se necesitan dos agregaciones de tipo texto y una de tipo numérico. Si incluimos las agregaciones de la siguiente forma: texto, texto, numérico, al guardar no habrá problema. Sin embargo, si volvemos a entrar en el informe o en el panel, convertirá la última agregación de tipo texto en numérica, lo que ocasionará errores en la consulta.

![error_tablas_cruzadas](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/b23ac46b-3896-4439-aa0a-91b1fb583a7e)

**Comment by juanSTIC** [comment]
Integrado en issue #77
