### ISSUE TITLE
Incidencia - EDA - Relaciones no siguen camino esperado

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#102]
Relacionado con: https://github.com/SinergiaTIC/SinergiaDA/pull/61
**Descripción**

Si al generar un informe hay dos posibles relaciones, no se está eligiendo la relación directa entre las tablas implicadas. En el siguiente ejemplo se han introducido campos de seguimientos, Pagos y Personas; los dos primeros campos tienen una relación directa con el segundo; sin embargo, la relación se establece a través del campo Organizaciones ausente en el informe.

![Screenshot from 2024-02-06 14-27-05](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/fa7bffe5-e762-4ec0-b871-11d2d31fc00f)
![Screenshot from 2024-02-06 14-27-25](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/ac613c74-033a-487f-abd3-a64ebf34ceb4)

**Información adicional** 

Se debería establecer la relación más directa teniendo en cuenta no solo el camino más corto, sino también los módulos de los campos presentes en el informe.

**Comment by jortilles** [comment]
@PaulaaSTIC  puedes poner el link del informe?

**Comment by jortilles** [comment]
Se crea el PR https://github.com/SinergiaTIC/SinergiaDA/pull/113
