### ISSUE TITLE
Incidencia - APP - Error en la suma de totales en tablas de referencia cruzada

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#110]
Se ha identificado un problema en una tabla de referencia cruzada que contiene valores decimales. Los problemas detectados son los siguientes:

1. **Suma errónea en los totales de fila**: Los totales de las filas no calculan correctamente la suma de los valores decimales.
2. **Totales de columna sin decimales**: En los totales de las columnas, los decimales no se muestran, lo que podría llevar a una representación incorrecta de los datos.

## Cómo reproducirlo

Para reproducir el problema, se puede ejecutar la siguiente consulta SQL en el entorno afectado:

```sql
select 'Getafe' as ciudad, 'Lechugas' as `Artículo`, 5.11 as Precio 
union select 'Madrid', 'Manzanas', 5.11
union select 'Barcelona', 'Manzanas', 5.11
union select 'Madrid', 'Naranjas', 5.11
union select 'Madrid', 'Tomates', 5.11
union select 'Madrid', 'Lechugas', 5.11
union select 'Madrid', 'Patatas', 5.11
union select 'Sevilla', 'Lechugas', 5.11
union select 'Getafe', 'Lechugas', 5.11
union select 'Valencia', 'Manzanas', 5.11
union select 'Barcelona', 'Manzanas', 5.70
union select 'Getafe', 'Tomates', 5.11
union select 'Getafe', 'Patatas', 5.11
union select 'Madrid', 'Patatas', 5.11
union select 'Sevilla', 'Lechugas', 5.11
union select 'Getafe', 'Tomates', 5.11
union select 'Getafe', 'Lechugas', 5.11
union select 'Valencia', 'Tomates', 5.11
union select 'Sevilla', 'Manzanas', 5.11
union select 'Barcelona', 'Lechugas', 5.11
union select 'Valencia', 'Tomates', 5.11

```

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/bf9c5e84-a495-4691-8d0d-92177819e777)

**Comment by asafJortilles** [comment]
@jortilles rama SDA#110

**Comment by jortilles** [comment]
Se crea pull recuest https://github.com/SinergiaTIC/SinergiaDA/pull/111
