### ISSUE TITLE
Incidencia - EDA - Error al eliminar permisos de grupo/usuario

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#121]
**Descripción**
Al eliminar un permiso de un usuario o grupo sobre una tabla, se eliminan todos los permisos guardados de ese usuario o grupo, afectando a los permisos sobre otras tablas.
 
El siguiente clip muestra el error en la eliminación de permisos. Se observa que al eliminar los permisos del usuario u1 sobre la tabla `Asistencias`, también se eliminan sus permisos sobre la tabla `Campañas`. Esto es incorrecto, ya que la eliminación de permisos debería ser específica para cada tabla.

![error_permisos](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/67945c8a-19af-4b79-8b9e-a20a74822de9)

**Comment by jortilles** [comment]
Se crea el PR https://github.com/SinergiaTIC/SinergiaDA/pull/122
