### ISSUE TITLE
Mejora - EDA - Posibilidad de cambiar títulos en los filtros

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#124]
Tenemos campos que se llaman igual y que aparecen en varios módulos (por ejemplo, Estado aparece en Eventos, Inscripciones, etc.). Si queremos incluir estos filtros a nivel de informe, lo ideal sería poder distinguirlos sin problema.

Por ejemplo, al agregar un filtro por el campo Nombre que existe en todos los módulos

**Comment by asafJortilles** [comment]
@jortilles listo para validar en rama SDA#124

**Comment by jortilles** [comment]
Creado PR https://github.com/SinergiaTIC/SinergiaDA/pull/155

**Comment by PaulaaSTIC** [comment]
Resuelto en: https://github.com/SinergiaTIC/SinergiaDA/pull/155
