### ISSUE TITLE
Incidencia -  APP + API - Permisos repetidos en al ejecutar updateModel

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#128]
## Descripción

Al ejecutar la función `updateModel` en SinergiaDA para modificar el modelo de datos, se encuentran el siguiente problema:

1. **Permisos de Grupo Repetidos**: Los permisos de grupo aparecen repetidos múltiples veces en la pantalla de gestión de la fuente de datos . Este problema se agrava cada vez que se ejecuta `updateModel`, incrementando el número de veces que cada permiso aparece repetido. Al intentar borrar uno de estos permisos duplicados, se eliminan todos los duplicados simultáneamente.
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/39d37396-8b0b-47a0-b6fd-99b5fefc6eef)

**Comment by jortilles** [comment]
Tener en cuenta que hay que gestionar los permisos que vienen de Sinergiada. Por ejemplo podemos poner una etiqueta FromSDA

**Comment by asafJortilles** [comment]
@jortilles revisar rama #128

**Comment by jortilles** [comment]
Creado PR https://github.com/SinergiaTIC/SinergiaDA/pull/142
