### ISSUE TITLE
Incidencia - API - Error en la aplicación de filtros de seguridad en paneles por usuarios no administradores

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#130]
## Descripción

Al crear o abrir paneles, los usuarios no administradores de SinergiaDA tienen problemas relacionados con la aplicación de la seguridad de grupos. Estos usuarios tienen permisos de grupo definidos a través de la ejecución de `updateModel`. Los problemas observados son:

1. **Ausencia de Seguridad de Grupos en el Módulo Principal**: La seguridad de grupos no se aplica sobre el módulo principal del panel, contraviniendo la expectativa de restricción basada en los permisos del grupo.

2. **Aplicación Indebida de Seguridad en Módulos Relacionados**: La seguridad de grupos se aplica a módulos relacionados que no están presentes en el panel. Esto sucede incluso si estos módulos relacionados no forman parte de la visualización del panel ni se utilizan en ningún filtro dentro del panel o a nivel de informe.

La seguridad de grupos debe aplicarse exclusivamente sobre el módulo principal del panel y sobre cualquier módulo que esté presente en el panel, ya sea por inclusión directa en la visualización o porque se utilice dentro de algún filtro del panel o a nivel de informe. No se debe aplicar seguridad de grupos a módulos ausentes en el panel.

**Comment by asafJortilles** [comment]
@juanSTIC no soy capaz de entrar en el usuario u1 para ver el ejemplo

**Comment by juanSTIC** [comment]
Pendiente de revisar e indicar en que PR se resuelve

**Comment by jortilles** [comment]
Se resuelve con el PR https://github.com/SinergiaTIC/SinergiaDA/pull/177

**Comment by jortilles** [comment]
Se puede hacer un informe donde apliquen dos grupos de seguridad a nivel de grupo y comprobarlo. Yo he hecho un infomre sobre asistencias. El usuario u2 tiene 2 grupos u1 y u2 y aplican los dos.
