### ISSUE TITLE
Incidencia - API -  No se aplican permisos si no hay registros para el grupo/módulo en la tabla sda_def_securitygroups_records

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#131]
## Descripción

Aunque se establezcan permisos a través de la ejecución de `updateModel`, los filtros de seguridad correspondientes no se aplican si no existen registros asociados al módulo/grupo específico en la tabla `sda_def_securitygroups_records`. Esto contradice el diseño esperado, donde los filtros de seguridad deben aplicarse independientemente de la existencia de registros en dicha tabla.

Los filtros de seguridad deben aplicarse a todos los usuarios con permisos de grupo definidos, sin importar la presencia o ausencia de registros en `sda_def_securitygroups_records`.

**Comment by asafJortilles** [comment]
Se corrige en SDA#135

**Comment by PaulaaSTIC** [comment]
Resolver este issue facilitaría la validación de los PRs de grupos de seguridad @jortilles
