### ISSUE TITLE
Incidencia - API -  Filtrado incompleto en queries para usuarios en múltiples grupos de seguridad

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#132]
## Descripción

Existe un problema en la ejecución de queries para usuarios que pertenecen a dos o más grupos diferentes. Actualmente, cuando se realiza una query que debería incluir filtros basados en todos los grupos a los que pertenece un usuario, sólo se está aplicando el filtro correspondiente al primer grupo.

Cuando un usuario pertenece a múltiples grupos, la lógica de filtrado de las queries debe considerar todos sus grupos de membresía para aplicar los filtros de seguridad correspondientes. Esto asegura que los resultados de las queries sean precisos y reflejen adecuadamente los permisos de acceso del usuario.
## Cómo reproducirlo

1. Asignar un usuario a dos o más grupos con diferentes permisos de acceso.
2. Realizar una query que debería aplicar los filtros de seguridad basados en la membresía de todos los grupos a los que pertenece el usuario.
3. Observar que los resultados de la query solo reflejan el filtrado basado en el primer grupo, omitiendo los filtros correspondientes a los grupos adicionales.

**Comment by asafJortilles** [comment]
@juanSTIC No he conseguido reproducir el error:
- He asignado al usuario permisos para SDA_G1 y SDA_G2, de forma que puede ver los módulos INSCRIPCIONES y PERSONAS en grupos SDA_G1 y SDA_G2, el módulo PAGOS en SDA_G1, y ASISTENCIAS solo en SDA_G2.
- Hago la consulta sobre los módulos PAGOS y ASISTENCIAS como muestro en la captura.
- En la consulta veo que sí que se usan los grupos necesarios:
- la consulta resultante se corresponde con los grupos de seguridad:
```
SELECT cast(sum(`sda_stic_payments`.`N`) as decimal(32,0) ) as `(n) Pagos`, `sda_stic_payments`.`assigned_user_name` as `Asignado a`, `sda_stic_attendances`.`description` as `Descripción`  
FROM sda_stic_payments 
 inner join `sda_stic_registrations` on `sda_stic_registrations`.`stic_payments_stic_registrationsstic_payments_ida` = `sda_stic_payments`.`id`  
 inner join `sda_contacts` on `sda_contacts`.`id` = `sda_stic_payments`.`stic_payments_contactscontacts_ida`  
 inner join `sda_stic_attendances` on `sda_stic_attendances`.`stic_payments_stic_attendancesstic_payments_ida` = `sda_stic_payments`.`id`  
where  (`sda_contacts`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SDA_G1'  and `table` =  'sda_contacts' )  
  or `sda_contacts`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SDA_G1'  and `table` =  'sda_contacts' )  
  )  
and (`sda_stic_payments`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SDA_G2'  and `table` =  'sda_stic_payments' )  
  or `sda_stic_payments`.`id`  in (select record_id from sda_def_security_group_records where `group` =  'SDA_G2'  and `table` =  'sda_stic_payments' )  
  )  
group by `sda_stic_payments`.`assigned_user_name`, `sda_stic_attendances`.`description` 
order by `(n) Pagos` Desc
```

![Image](https://github.com/SinergiaTIC/SinergiaDA/assets/122270752/61a31778-00fe-4cd9-ac39-577be003920a)

**Comment by jortilles** [comment]
@ronaldchavezjortilles

**Comment by jortilles** [comment]
Se soluciona con el PR  https://github.com/SinergiaTIC/SinergiaDA/pull/188
