### ISSUE TITLE
Incidencia - API - Incorporación incompleta de permisos a nivel de usuario en el modelo de datos tras ejecutar updateModel.

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#133]
## Descripción

Se ha detectado un problema en el proceso de actualización del modelo de datos en SinergiaDA a través de la ejecución del método `updateModel`. Aunque la tabla `sda_def_permissions` recopila correctamente los permisos a nivel de usuario ( no únicamente a nivel de grupo), estos permisos específicos del usuario no se reflejan en el modelo de datos actualizado. Como consecuencia, los usuarios no tienen acceso a sus propios registros( aquellos registros donde el campo `assigned_user_name` coincide con el nombre del usuario.)

Tras la ejecución de `updateModel`, todos los permisos definidos a nivel de usuario en la tabla `**sda_def_permissions**` deben trasladarse al modelo de datos, permitiendo el acceso del usuario a los registros específicos donde el campo `assigned_user_name` coincide con su nombre. 

NOTAS:
Estos permisos deben aplicarse de manera dinámica a través de los registros de la tabla **sda_def_permissions** con valor _ACL_ALLOW_GROUP_priv_  o _ACL_ALLOW_OWNER_ en la columna **stic_permission_source**  comparando el valor indicado en la columna _assigned_user_name_ con el nombre del usuario activo. 
El filtro resultante de esta lógica debe aplicarse mediante **OR** acompañando al resto de filtros de seguridad que corresponda implementar en cada caso.

**Comment by jortilles** [comment]
Este issue se  ha solucionado también en el pr https://github.com/SinergiaTIC/SinergiaDA/pull/143 

El cambio es en el archivo eda/eda_api/lib/module/updateModel/updateModel.controller.ts la línea  107

**Comment by juanSTIC** [comment]
Implica cambios en SinergiaCRm al crear la tabla sda_def_permissions y cambios en SinergiadA para incorporarlos mediante updateModel

**Comment by jortilles** [comment]
@ronaldchavezjortilles

**Comment by jortilles** [comment]
Se soluciona con el PR https://github.com/SinergiaTIC/SinergiaDA/pull/178
