### ISSUE TITLE
Incidencia - API - Error al establecer tabla principal en una query con grupos de seguridad

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#134]
## Descripción
Un usuario experimenta un problema al crear un panel que incluye un único campo del módulo *Personas*. La query generada por el sistema se basa erróneamente en el módulo *Inscripciones* en lugar del módulo *Personas*. Este comportamiento ocurre incluso cuando el usuario tiene acceso a los registros de su grupo en los módulos *Personas*, *Inscripciones* y *Asistencias*. Sin embargo, si se agrega al panel un campo de un módulo al cual el usuario no tiene permisos, la query se reformula correctamente y el módulo principal pasa a ser *Personas*.

## Cómo reproducirlo
1. Acceder al sistema con un usuario que tenga acceso exclusivamente a los registros en los módulos *Personas*, *Inscripciones* y *Asistencias*.
2. Crear un panel nuevo y agregar un único campo del módulo *Personas*.
3. Observar que la query se formula incorrectamente basándose en el módulo *Inscripciones*.
4. Agregar un campo de un módulo al cual el usuario no tiene acceso.
5. Verificar que la query se reformula correctamente, estableciendo a *Personas* como el módulo principal.

**Comment by asafJortilles** [comment]
@juanSTIC No he conseguido reproducir el error.
- He cogido un usuario, le he asignado un grupo de seguridad al que solo tiene acceso los 3 módulos que citas.
- Hago una consulta con una columna del módulo "Personas" (sda_conacts), pero siempre se hace la consulta desde el modulo sda_contacts. 
- he intentado hacer la consulta con una columna distinta en varias ocasiones, pero no he conseguido reproducir el error

Añado captura:



![Image](https://github.com/SinergiaTIC/SinergiaDA/assets/122270752/93a2326e-7de1-4076-bede-be919d0dad30)

**Comment by juanSTIC** [comment]
duplicado #175
