### ISSUE TITLE
Incidencia - API - Fallo en updateModel al actualizar pertenencia a grupos de seguridad

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#135]
## Descripción
Existe un problema donde, si un usuario no administrador tiene acceso a algún grupo de seguridad, la función `updateModel` no actualiza su pertenencia a grupos de seguridad a pesar de que estos estén correctamente definidos en la tabla `sda_def_permissions`. Esto resulta en que no es posible actualizar los grupos de seguridad de un usuario sin antes eliminar al usuario del sistema. Se espera que `updateModel` realice esta actualización automáticamente sin necesidad de eliminar al usuario.

## Cómo reproducirlo
1. Verificar que un usuario no administrador esté asignado a un único grupo de seguridad.
2. Asegurarse de que los grupos de seguridad a los que se desea actualizar la pertenencia del usuario están correctamente definidos en la tabla `sda_def_permissions`.
3. Ejecutar `updateModel` intentando actualizar la pertenencia a grupos de seguridad del usuario.
4. Observar que `updateModel` no actualiza la pertenencia a grupos de seguridad como se esperaba.

**Comment by asafJortilles** [comment]
@juanSTIC Estoy intentando reproducir el problema pero no lo consigo. Si es posible mañana viernes nos conectamos un momento y lo vemos.

**Comment by asafJortilles** [comment]
@jortilles revisar rama SDA#135

**Comment by asafJortilles** [comment]
@jortilles listo para validación

**Comment by jortilles** [comment]
Se crea el pr https://github.com/SinergiaTIC/SinergiaDA/pull/143
