### ISSUE TITLE
Mejora - EDA - Incluir filtro "Año pasado completo"

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#141]
#### Descripción
El filtro "el año pasado" puede causar confusión, ya que solo captura la parte del año anterior desde el inicio hasta la fecha actual de este año. No existe la opción de seleccionar todo el año pasado, como sí ocurre con los meses o las semanas.

#### Solución propuesta
Se propone la creación de un nuevo filtro llamado "Año pasado completo".

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/4acb5c08-39c7-4b27-84c3-faf3ab58a9ea)

**Comment by asafJortilles** [comment]
@PaulaaSTIC tenemos esta función ya implementada en EDA, lo tendréis disponible en la próxima sincornización.

**Comment by jortilles** [comment]
Nos lo traemos

**Comment by jortilles** [comment]
Se crea el PR https://github.com/SinergiaTIC/SinergiaDA/pull/192
