### ISSUE TITLE
Incidencia/Mejora - API+APP - No hay filtros dinámicos

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#145]
### Descripción
Los filtros de fechas en los paneles no permiten usar rangos dinámicos. Esto es necesario para poder hacer informes que muestren datos actualizados basados en periodo, número de días, año actual, mes actual, etc.

### Descripción
Los filtros de fecha a nivel de informe permiten aparentemente hacer filtros sobre rangos dinámicos de fechas. Sin embargo, una vez seleccionado, las fechas de inicio y fin quedan fijadas en el filtro de manera literal, perdiendo así el dinamismo. Por ejemplo, si se selecciona "esta semana", el filtro que se aplica es:

```sql
WHERE `sda_stic_payments`.`payment_date` BETWEEN STR_TO_DATE('2024-05-13', '%Y-%m-%d') AND STR_TO_DATE('2024-05-17 23:59:59', '%Y-%m-%d %H:%i:%S')
```
Con esto, la próxima semana ya no se mostrarán los datos "de la semana actual". El filtro aplicado debería ser:

```sql
WHERE `sda_stic_payments`.`payment_date` 
BETWEEN 
  DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY)
AND 
  DATE_ADD(DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY), INTERVAL 6 DAY)
```
Esto garantizaría que los datos siempre correspondan a la semana actual.

**Comment by jortilles** [comment]
Esto ya existe.
