### ISSUE TITLE
Mejora - SDA -  Desactivar paneles SQL de filtros de informe.

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#164]
En los filtros a nivel informe, desactivar la aplicación del filtro en los paneles SQL para que el usuario no deba hacerlo manualmente.

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/55d6de7a-3d52-4a2b-bd2f-57ef5578e37b)

**Comment by jortilles** [comment]
@ronaldchavezjortilles

**Comment by jortilles** [comment]
Se crea PR https://github.com/SinergiaTIC/SinergiaDA/pull/176

**Comment by jortilles** [comment]
Este issue se puede cerrar?

**Comment by PaulaaSTIC** [comment]
Resuelto en: https://github.com/SinergiaTIC/SinergiaDA/pull/176
