### ISSUE TITLE
Incidencia - EDA - SDA - Se ha perdido la compatibilidad con el modo EDA

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#166]
En la rama reporting no es posible cargar informes creados en el modo EDA que contengan relaciones. 

No se genera ningún error, pero los informes se muestran vacío.

**Como reproducirlo**
1. Usando la rama _master_ crear un informe que contenga alguna relación entre módulos
2. Cambiar a la rama _reporting_ y comprobar que el informes se carga, pero no se muestran datos (ni el aviso NO DATA)

**Comment by PaulaaSTIC** [comment]
Resuelto en: https://github.com/SinergiaTIC/SinergiaDA/pull/167
