### ISSUE TITLE
Incidencia - EDA - Se pierden las agregaciones sobre campos de texto en el modo EDA

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#170]
Hemos comprobado un error en el manejo de las agregaciones en los campos de texto (Cuenta valores o Cuenta valores distintos) en un informe en modo EDA, tras guardar y recargar el valor, que había trasformado previamente en numérico, vuelve a ser texto y la consulta no ofrece resultado.

Cómo reproducirlo
- En un informe en modo EDA, sobre cualquier campo de tipo texto, añadir una agregación (cuenta valores) y crear un KPI. Guardar y recargar la página.

**Comment by PaulaaSTIC** [comment]
Resuelto en: https://github.com/SinergiaTIC/SinergiaDA/pull/172
