### ISSUE TITLE
Incidencia -  EDA - No es posible crear un KPI sobre un campo de tipo  fecha

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#171]
No se puede crear un KPI sobre un campo de tipo fecha. A pesar de que EDA permite añadir la agregación Cuenta valores o Cuenta valores distintos, y ofrece un resultado, este no puede ser convertido en un KPI, por que se mantiene como un campo de tipo string.

**Comment by ronaldchavezjortilles** [comment]
@ronaldchavezjortilles

**Comment by jortilles** [comment]
Creado PR https://github.com/SinergiaTIC/SinergiaDA/pull/189
