### ISSUE TITLE
Incidencia -  API - Aplicación indebida de permisos de grupo sobre tabla incorrecta

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#175]
Según se ve en la imagen, al construirse una consulta que exclusivamente usa datos de _sda_contacts_, la condición que aplica la seguridad de grupo se hace sobre otra tabla, en este caso _sda_stic_sepe_actions_, que no está presente en la query.
En este caso solo debería aplicarse sobre __sda_contacts_
![ksnip_20240624-151218](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/5a742adc-b17d-4681-9229-fdac42369faa)

**Comment by jortilles** [comment]
Creado PR https://github.com/SinergiaTIC/SinergiaDA/pull/177

**Comment by juanSTIC** [comment]
Resuelto en el PR #177
