### ISSUE TITLE
Incidencia - API - Visualización de paneles  con seguridad y sin datos 

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#182]
Paneles sin acceso:

Si un usuario no administrador accede a un informe donde el módulo principal de un panel es un módulo al que no tenemos acceso, deberíamos mostrar un mensaje indicando que no se tiene acceso a los datos. Podríamos hacerlo con un mensaje en el panel: "Este panel no está disponible por falta de permisos". Esto debe ocurrir tanto si en el panel solo aparecen campos de este módulo como si aparecen de otros módulos a los que sí tenemos acceso. Si el módulo principal no es visible para nosotros, debe aparecer dicho mensaje, ya que la consulta no se puede cargar correctamente. Actualmente, hay un comportamiento diferente que puede generar confusión.

**Comment by jortilles** [comment]
Se soluciona con el pr  https://github.com/SinergiaTIC/SinergiaDA/pull/188
