### ISSUE TITLE
Incidencia - EDA - No se elimina filtro de informe 

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#186]
Hay ocasiones en las que, al intentar eliminar un filtro de informe, se muestra una pantalla en blanco y no se puede eliminar.

**Pasos para reproducir el problema:**

1. Crear un filtro sin seleccionar ningún panel.
2. Guardar el informe.
3. Intentar eliminar el filtro.
4. Observar que no se puede eliminar y que se muestra una pantalla en blanco.
5. 

![filtro no eliminable](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/001f1874-588b-4b84-969b-b91d3a80b242)

**Comment by jortilles** [comment]
@ronaldchavezjortilles

**Comment by ronaldchavezjortilles** [comment]
Solucionado para el uso del filtro con todos los valores desactivados. Ya podemos recuperar la configuración del filtro y la pantalla en blanco ya no tendrá porque mostrarse. Permitiendo la eliminación del filtro global.

**Comment by jortilles** [comment]
Se crea el PR https://github.com/SinergiaTIC/SinergiaDA/pull/230
