### ISSUE TITLE
Incidencia - EDA - Error paneles SQL si una lista tiene campos vacios. 

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#196]
Hemos observado que la siguiente consulta SQL produce un error. Al ejecutar la consulta en SDA, se genera el siguiente mensaje en el log: `TypeError: Cannot read properties of undefined (reading '0')`. Sin embargo, esta misma consulta no produce un error si la ejecutamos directamente en la base de datos. Haciendo pruebas, hemos identificado que esto se produce porque en el tipo de relación hay campos que no tienen valores, pero este error no debería producirse.

```
SELECT `sda_l_stic_accounts_relationships_relationship_type_stic_account`.`value` as `Tipo de relación`, 
sum(case when year(`sda_stic_accounts_relationships`.`start_date`) >= year(curdate()) then 1 else 0 end) as 'Altas año en curso', 
sum(case when year(`sda_stic_accounts_relationships`.`start_date`) < year(curdate()) then 1 else 0 end) as 'Altas anteriores',
count(`sda_stic_accounts_relationships`.`N`) as 'Total'

FROM sda_stic_accounts_relationships 

inner join `sda_l_stic_accounts_relationships_relationship_type_stic_account` on `sda_l_stic_accounts_relationships_relationship_type_stic_account`.`code` = `sda_stic_accounts_relationships`.`relationship_type`  

where  `sda_l_stic_accounts_relationships_relationship_type_stic_account`.`value` is not null AND `sda_stic_accounts_relationships`.`active` = '1'

group by `sda_l_stic_accounts_relationships_relationship_type_stic_account`.`value`
```

**Comment by jortilles** [comment]
@ronaldchavezjortilles

**Comment by ronaldchavezjortilles** [comment]
La query es correcta, al verificar la usabilidad en la aplicación creo que falto agregar una tabla de origen, he probado agregando una tabla de origen y funciona correctamente. 



![Captura de pantalla 2024-10-08 110711](https://github.com/user-attachments/assets/82e780d5-d326-4520-ab93-8e821eea77d1)

**Comment by jortilles** [comment]
Volvemos a generar la situación

**Comment by PaulaaSTIC** [comment]
Actualmente no se genera ningún error, por lo que cerramos el issue
