### ISSUE TITLE
Incidencia - EDA - TypeError en modo SQL 

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#199]
La siguiente consulta SQL genera un error al ejecutarse en el modo SQL de SDA, aunque al ejecutarla directamente en la base de datos, devuelve el resultado esperado (como se muestra en la imagen). En el log, se registra el siguiente error: `TypeError: Cannot read properties of undefined (reading '0').
`
![image](https://github.com/user-attachments/assets/c52c9ea8-455f-4356-b709-cde7ae013d15)
```
SELECT
   CASE
        WHEN `sda_contacts`.`stic_age_c` BETWEEN 0 and 5 THEN '0 - 5 anys'
        WHEN `sda_contacts`.`stic_age_c` BETWEEN 6 and 10 THEN '6 - 10 anys'
        WHEN `sda_contacts`.`stic_age_c` BETWEEN 11 and 15 THEN '11 - 15 anys'
        WHEN `sda_contacts`.`stic_age_c` BETWEEN 16 and 20 THEN '16 - 20 anys'
        WHEN `sda_contacts`.`stic_age_c` > 20 THEN '21 o més anys'
        WHEN `sda_contacts`.`stic_age_c` IS NULL THEN ' '
    END as Rango_Edad,
   count(distinct `sda_contacts`.`id`) as "N"
FROM sda_contacts
inner JOIN `sda_stic_registrations` ON  `sda_contacts`.`id` = `sda_stic_registrations`.`stic_registrations_contactscontacts_ida`
inner JOIN `sda_stic_events` ON  `sda_stic_registrations`.`stic_registrations_stic_eventsstic_events_ida` = `sda_stic_events`.`id`
where  (`sda_stic_events`.`subevento2_c`  in ('ACTIVIDAD VERANO')  )
GROUP BY Rango_Edad
```

**Comment by jortilles** [comment]
@ronaldchavezjortilles

**Comment by ronaldchavezjortilles** [comment]
La query es correcta y he verificado que con la ayuda de alias al momento de construir la query funciona adecuadamente. 

Dejo la misma query con el alias "c" para la tabla sda_contacts.

	SELECT
	   CASE
	        WHEN c.`stic_age_c` BETWEEN 0 and 5 THEN '0 - 5 anys'
	        WHEN c.`stic_age_c` BETWEEN 6 and 10 THEN '6 - 10 anys'
	        WHEN c.`stic_age_c` BETWEEN 11 and 15 THEN '11 - 15 anys'
	        WHEN c.`stic_age_c` BETWEEN 16 and 20 THEN '16 - 20 anys'
	        WHEN c.`stic_age_c` > 20 THEN '21 o més anys'
	        WHEN c.`stic_age_c` IS NULL THEN ' '
	    END as Rango_Edad,
	   count(distinct c.`id`) as "N"
	FROM sda_contacts c
	inner JOIN `sda_stic_registrations` ON c.`id` = `sda_stic_registrations`.`stic_registrations_contactscontacts_ida`
	inner JOIN `sda_stic_events` ON  `sda_stic_registrations`.`stic_registrations_stic_eventsstic_events_ida` = `sda_stic_events`.`id`
	where  (`sda_stic_events`.`subevento2_c`  in ('ACTIVIDAD VERANO')  )
	GROUP BY Rango_Edad

**Comment by jortilles** [comment]
En la actualidad si se puede filtrar en los paneles SQL  poniendo alias y haciendo referencia a la tabla principal de la consulta.

Para los campos desplegables debemos definir el comportamiento. Actualmente tenemos dos opciones. Hacer referencia al campo principal o hacer referencia al campo de la tabla accesoria.

and ${c.stic_gender_c}

------------------------------- VS 


left join `sda_l_contacts_stic_gender_c_stic_genders_list`    ls  on ls.`code` = c.`stic_gender_c` 
 
 
and ${ls.value}

**Comment by ronaldchavezjortilles** [comment]
Hemos verificado con Juanjo y hemos agregado unos cambios para asegurar la query.

**Comment by jortilles** [comment]
Se crea el pr https://github.com/SinergiaTIC/SinergiaDA/pull/229

**Comment by juanSTIC** [comment]
Ya mergeado
