### ISSUE TITLE
Incidencia - EDA - SDA - Usuarios de grupo pueden crear informes públicos

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#201]
## Descripción

Actualmente un usuario perteneciente a un grupo con filtros de seguridad aplicados a sus informes puede crear un informe privado, común o de grupo que automáticamente aplica estos filtros de seguridad. Sin embargo, posteriormente pueden convertir este informe a estado "Público". Cuando se abre a través de URL, este informe público permite ver todos los datos sin ningún filtro de seguridad aplicado, potencialmente exponiendo información sensible.

Esto crea una brecha de seguridad donde los usuarios pueden eludir las restricciones de acceso a datos asignadas.

## Solución Propuesta

Para abordar este problema de seguridad, necesitamos restringir la capacidad de hacer informes públicos solo a los administradores. Este cambio debe implementarse en dos áreas clave:

1. En el componente `home-sda`:
2. En la interfaz de edición de informes:

**Comment by jortilles** [comment]
Esto se cierra con el pr de juan.... entiendo
