### ISSUE TITLE
Incidencia - API - Pérdida de acceso al modificar datos de usuario

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#207]
**Descripción del problema**
Cuando se modifica cualquier dato en un usuario de SDA (no procedente de SinergiaCRM), como por ejemplo la pertenencia a grupos, el usuario pierde el acceso a la aplicación y la contraseña debe ser generada nuevamente.

**Cómo reproducir el problema**
1. Acceder a la gestión de usuarios en SDA
2. Seleccionar un usuario no procedente de SinergiaCRM
3. Modificar cualquier dato del usuario (por ejemplo, la pertenencia a grupos)
4. Guardar los cambios
5. Intentar acceder a la aplicación con las credenciales del usuario modificado
6. Comprobar que el acceso es denegado y se requiere una nueva generación de contraseña

**Comment by jortilles** [comment]
Resuelto en el pr indicado

**Comment by juanSTIC** [comment]
Resuelto en #212
