### ISSUE TITLE
Incidencia - API - Pérdida de permisos y pertenencia a grupos al ejecutar update model

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#208]
**Descripción del problema**
Se han identificado dos problemas relacionados con la ejecución de update model:

1. Los permisos de grupos creados en SDA sobre tablas de la fuente de datos SinergiaDA (proveniente de SinergiaCRM) se pierden al ejecutar update model.

2. La pertenencia de usuarios creados en SDA en grupos provenientes de SinergiaCRM se pierde al ejecutar update model.

**Cómo reproducir el problema 1**
1. Crear un grupo cualquiera directamente en SinergiaDA
2. Asignarle permisos sobre tablas de la fuente de datos SinergiaDA
3. Ejecutar updateModel
4. Verificar que los permisos establecidos se han perdido.

**Cómo reproducir el problema 2**
1. Crear un usuario en SinergiaDA
2. Asignarle a un grupo proveniente de SinergiaCRM (prefijo SDA_)
3. Ejecutar updateModel
4. Verificar que el usuario ha desaparecido del grupo

**Comportamiento esperado**
Después de ejecutar update model:
- Los permisos de grupos creados en SDA sobre tablas de SinergiaDA deberían mantenerse.
- La pertenencia de usuarios creados en SDA a grupos provenientes de SinergiaCRM debería permanecer intacta.

**Comment by jortilles** [comment]
Se cierra con el pr indicado
