### ISSUE TITLE
Incidencia -  API - Permisos de grupo restringen acceso a usuarios que no deberían tener restricción de grupo

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#232]
**Descripción del problema**
La aplicación actual de restricciones de grupo mediante roles y Ver="Grupo" al trasladarse a SinergiaDA se aplica de manera incorrecta. Esto provoca que, si en un mismo grupo hay usuarios con distintos niveles de acceso a un módulo (por ejemplo, Personas), las restricciones más limitadas se aplican indebidamente a todos los usuarios del grupo, incluso a aquellos que deberían tener acceso completo.

**Cómo reproducir el problema**
1. Configurar un grupo con usuarios que tienen diferentes niveles de acceso al módulo Personas.
2. Asignar a un usuario (u1) acceso a todos los registros de Personas.
3. Asignar a otro usuario (u2) acceso solo a los registros de su grupo de seguridad.
4. Intentar acceder a los registros de Personas con el usuario u1.
5. Comprobar que u1 solo puede ver los registros del grupo de seguridad, en lugar de todos los registros.

**Comportamiento esperado**
Cada usuario debería tener acceso a los registros según su nivel de permisos individual, independientemente de las restricciones aplicadas a otros usuarios del mismo grupo.

**Solución propuesta**
1. Modificar la lógica en SinergiaDA:
   - En la función updateModel, aplicar el filtro de grupo a nivel de usuario en lugar de a nivel de grupo.
   - La query del filtro de grupo debe ser igual a la actual.

2. Modificar SinergiaCRM:
   - En el proceso de rebuild, añadir la información del usuario en cada línea de la tabla sda_def_permissions, además de la información del grupo que ya se incluye.

**Comment by jortilles** [comment]
Acabo de hacer commit. Yo creo que con este cambio ya se corrige. Voy a hacer pruebas. Pero si queréis probar por vuestra parte para aseguraros creo que ya podéis. @juanSTIC  @PaulaaSTIC  @ronaldchavezjortilles

**Comment by jortilles** [comment]
Este issue se puede cerrar
