### ISSUE TITLE
Incidencia - EDA - Query Builder usa relación erronea 

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#45]
## Descripción
Al generar un informe que utiliza las tablas Personas, Inscripción y Eventos, sin aplicar filtros, se observa un uso incorrecto de la tabla Users. El SQL generado incluye una relación con esta tabla, a pesar de que no se ha incluido ningún campo de ella. Este comportamiento produce errores evidentes en los datos obtenidos.

El SQL resultante es:

```sql
SELECT 
    sda_contacts.first_name AS Nombre, 
    sda_stic_registrations.name AS Nombre_Inscripción, 
    sda_stic_events.name AS `Nombre Evento`
FROM 
    sda_contacts
INNER JOIN 
    sda_stic_registrations ON sda_stic_registrations.stic_registrations_contactscontacts_ida = sda_contacts.id
INNER JOIN 
    sda_users ON sda_users.id = sda_contacts.assigned_user_id
INNER JOIN 
    sda_stic_events ON sda_stic_events.assigned_user_id = sda_users.id
GROUP BY 
    sda_contacts.first_name, 
    sda_stic_registrations.name, 
    sda_stic_events.name
ORDER BY 
    Nombre DESC

```

## Como reproducirlo
1. Crear un informe utilizando los campos Nombre de las tablas Personas, Inscripción y Eventos.
2. No aplicar ningún filtro que involucre la tabla Users.
3. Observar el SQL generado.

![Image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/5e873a48-0ac2-4bf2-bbed-bb0c00e3f706)

**Comment by jortilles** [comment]
El comportamiento es "Correcto" aunque no el esperado. EDA no prioriza un camino por encima de otros.   Y al existir un camino a través de la tabla users EDA sigue ese camino. 

Se ha realizado un ajuste para que  se prioricen las relaciones directas. Es decir. Si hay una relación directa entre las tablas implicadas se priorizará sobre otros caminos más largos.  Esto no permite elegir el camino. Simplemente si hay un camino directo se prioriza sobre otro que necesite de tablas intermedias.

**Comment by juanSTIC** [comment]
hecho
