### ISSUE TITLE
Incidencia - EDA - Filtros de informe no permiten la edición

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#46]
## Descripción
Al acceder a informes previamente generados, nos hemos encontrado el siguiente problema. Al intentar modificar los ajustes de varios filtros, el diálogo de filtros completo no se muestra, lo que impide realizar modificaciones en el filtrado.

![Screenshot from 2023-11-28 18-10-11](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/2ada90ba-b0a8-4464-977f-7771e45fd965)

## Información adicional
Este comportamiento no se observa en todos los informes y ha sido notado desde la última actualización.

**Comment by asafJortilles** [comment]
@PaulaaSTIC podrías por favor hacer el informe público para ver como se reproduce el problema? Gracias.

**Comment by PaulaaSTIC** [comment]
Os paso la URL pública: https://futsaliris.sinergiada.org/en/#/public/65661bba9420176a268eb112 . Este es un error que no hemos conseguido replicar en otras instancias, y no sabemos por qué está ocurriendo. He ajustado la prioridad y la he cambiado a alta.

**Comment by asafJortilles** [comment]
@PaulaaSTIC Este error sucede porque hay alguna inconsistencia en el modelo de datos. Si abres la consola al abrir el filtro, verás lo siguiente:


![Image](https://github.com/SinergiaTIC/SinergiaDA/assets/122270752/cdf02002-0072-4c0e-b446-8d52812abd20)

El error es el siguiente: `ERROR TypeError: Cannot read properties of undefined (reading 'table_name')`
Cuando nos encontramos este error, lo más probable es que estamos intentando usar una tabla que no se encuentra en el modelo. 

Podrías revisar si es mi suposición correcta? 

Como solución, además de revisar de que el informe se adecua a la situación actual de las entidades consultadas, podríamos hacer algún mensaje de error o sacar en consola algún mensaje, por si nos volvemos a encontrar esta situación en el futuro.  

Espero tus comentarios al respecto.

**Comment by PaulaaSTIC** [comment]
He vuelto a llamar al updateModel para regenerar el modelo de datos. El error solo se produce en la primera fila de filtros (en todos ellos), mientras que en el resto del informe sí funcionan. He incluido de nuevo uno de los filtros que daba error, 'Tipus Ingrés/Despesa:', y ahora se puede editar.

**Comment by jortilles** [comment]
Hola @PaulaaSTIC  Asaf me comenta que está pendiente de que podamos reproducir el problema.... Hay alguna manera de regenerar el informe?

**Comment by PaulaaSTIC** [comment]
En estos momentos no se reproduce la incidencia
