### ISSUE TITLE
Incidencia - EDA - Filtros de panel ausentes en la edición

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#47]
## Descripción
Se han identificado filtros de panel que figuran en el resumen de filtros pero no en la sección de edición de filtros, lo que impide su modificación.

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/125350097/6cb10aee-c46d-4193-961a-98751a93a8b8)

## Reproducir el problema

1. Seleccionar un informe ya generado.
2. Elegir un panel.
3. Observar que en el resumen de filtros aparece un filtro que no está presente en la sección "Filtrar los resultados por:".

**Comment by asafJortilles** [comment]
@PaulaaSTIC no soy capaz de reproducirlo, podrías dirigirme hacia algún panel público para verlo?
