### ISSUE TITLE
Incidencia - EDA - Error al eliminar filtro de un panel

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#48]
## Descripción 

Se han encontrado informes con varios filtros, en los que al eliminar el primer filtro, se elimina el segundo en su lugar.

## Pasos para reproducir el problema

1. Acceder a un informe específico.
2. Seleccionar un panel que tenga al menos un filtro en la sección "Filtrar los resultados por".
3. Añadir un segundo filtro al panel seleccionado.
4. Eliminar el primer filtro y observar que, en lugar de eliminar el filtro deseado, se elimina el segundo filtro.

Además no permite editar el primer filtro.

**Comment by asafJortilles** [comment]
esto lo estoy revisando yo
