### ISSUE TITLE
Incidencia - EDA - Mejora en el padding de los KPI

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#49]
## Descripción
Una de las mejoras claras a nivel visual de la aplicación es la adecuación del tamaño de los KPI al tamaño del panel. Actualmente, el tamaño de los KPI no se ajusta adecuadamente cuando el número tiene muchas cifras, lo que resulta en un aprovechamiento insuficiente del espacio disponible. La propuesta es reducir el padding de los KPI para maximizar el uso del espacio.
![243958146-63b8b6ee-0b5f-413b-9c72-91a387a0e337](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/f3178351-f7b8-4c87-9847-21d19d938416)

## Como reproducirlo
1. Observar el tamaño actual de los KPI en la aplicación.
2. Dimensionar el cuadro de KPI y notar cómo el tamaño no se ajusta óptimamente a los márgenes disponibles.

## Solución propuesta
Reducir considerablemente el padding de los KPI para aprovechar al máximo el espacio disponible en el panel. Esto incluye ajustes para centrar verticalmente los KPI en el caso de que presenten muchas cifras, asegurando así una mejor visualización y aprovechamiento del espacio.

**Comment by jortilles** [comment]
Creado pr. https://github.com/SinergiaTIC/SinergiaDA/pull/114
