### ISSUE TITLE
Incidencia - EDA - Error en la suma de filas con ceros en tablas cruzadas

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#50]
## Descripción
En tablas cruzadas, se ha detectado que la suma del total de algunas de las filas es errónea. Este error parece ocurrir cuando aparecen ceros en algunas de las casillas que deben sumarse, provocando que se sumen otras celdas incorrectamente. El problema se presenta al sumar un conjunto de columnas, pero no en otros.
![image_720](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/46187267/961001d1-d544-4fa1-94c9-7261ef15b526)

## Cómo reproducirlo
1. Crear o abrir una tabla cruzada que contenga ceros en algunas de las celdas.
2. Observar que la suma del total de algunas filas no es la esperada y parece sumar celdas incorrectas.

## Solución propuesta
Revisar y corregir la lógica de cálculo de la suma del total de filas en tablas cruzadas, asegurándose de que las celdas con cero se manejen correctamente.

**Comment by asafJortilles** [comment]
@juanSTIC podrías por favor compartir el ejemplo que has hecho?

**Comment by juanSTIC** [comment]
> @juanSTIC podrías por favor compartir el ejemplo que has hecho?

Acabo de reproducirlo en el informe https://demo.sinergiada.org/es/#/dashboard/6479c9e7370bfcbee8a59cb0

![image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/694e2dd7-5bce-467a-9a43-29c7be7b7585)

**Comment by jortilles** [comment]
Se revisa el PR y se propone un nuevo enfoque
