### ISSUE TITLE
Incidencia - EDA -  Etiquetas incorrectas en totales/subtotales de columna/fila

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#51]
Al editar opciones de gráfico en modo tabla, al realizar cambios en las opciones de totales/subtotales, se observa una incorrecta correspondencia entre mostrar u ocultar Totales en filas y columnas.

En el caso de las tablas "simples", solo se muestran los Totales de Columna, lo cual es adecuado. Sin embargo, la opción de "subtotal de fila" carece de sentido en este contexto y no debería estar disponible. Además, al aplicar subtotales, los valores mostrados resultan confusos, ya que no parecen estar agregando filas por valores categóricos.

Por otro lado, en las tablas "cruzadas", se muestra correctamente la opción de Totales de Columna, que tiene sentido. Sin embargo, tanto los subtotales como los totales parecen ser redundantes, ya que no aportan información adicional y dan el mismo valor.

Se requiere una revisión completa de las funciones y los textos utilizados en esta sección. Además, se debe abordar el problema relacionado con los colores en las tablas en catalán, que no funcionan correctamente.

El problema de los subtotales y totales se reproduce tanto en castellano como en catalán.

Es necesaria una revisión a fondo de las funciones y textos de este apartado.
![image](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/46187267/7c596767-1b48-43bb-81db-e8ba4c8d04b6)
![image](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/46187267/eb345f8d-8e24-4095-a6e4-f64710fd1314)

![image](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/46187267/d3d4bc52-34f7-4e21-b366-ca04e3cadfe4)
![image](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/46187267/c74567be-7aff-4063-a631-cd48aefb5abc)
![image](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/46187267/d0a79c25-03e2-4c4e-bdd6-5d748e5259d9)

**Comment by asafJortilles** [comment]
@jortilles rama SDA·51

**Comment by jortilles** [comment]
Se crea PR https://github.com/SinergiaTIC/SinergiaDA/pull/254
