### ISSUE TITLE
Mejora - EDA -  Permitir gestión de múltiples relaciones entre tablas

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#53]
En SinergiaDA, es común encontrar múltiples relaciones entre dos tablas, algunas de las cuales forman parte del núcleo de SinergiaCRM, como las relaciones entre las tablas de 'Pagos' y 'Personas'. Además, es común que las entidades creen sus propias relaciones adicionales.

Actualmente, EDA sólo permite el uso directo de la primera relación entre dos tablas a través de su interfaz de diseño de consultas. Aunque las relaciones adicionales están definidas en las tablas de metadatos (sda_def_relationships) y en el modelo de datos en EDA, no se pueden utilizar de manera directa a través de la interfaz de diseño de consultas. Aunque se pueden utilizar a través de SQL directo, esto no es ideal.

Se propone establecer un mecanismo en la interfaz de diseño de consultas de EDA que permita elegir, cuando existen múltiples relaciones entre dos tablas, qué relación específica se desea usar en la consulta.

**Comment by juanSTIC** [comment]
Concreción de la propuesta:

1. **Selección de Relaciones**: Implementar un menú desplegable _select_ junto a cada campo, ofreciendo como opciones todas las posibles relaciones que pueden vincular dicho campo con cualquier otro campo ya presente en la consulta.
   
2. **Relación Predeterminada**: Por defecto, el sistema seleccionará automáticamente la relación más corta entre el campo en cuestión y cualquier módulo incluido en la consulta. En situaciones donde existan múltiples relaciones directas viables, se optará por la relación que involucre al módulo ubicado más a la izquierda en el panel (considerado el módulo principal).

3. **Visualización de Nombres de Relaciones**: Mostrar en el menú desplegable los nombres de las relaciones, los cuales se obtendrán de la columna _label_ de la tabla _sda_def_relationships_.

4. **Manejo de Relaciones Indirectas**: En casos donde no exista una relación directa y se recurra a una relación indirecta (por ejemplo, entre Personas y Eventos a través del módulo Inscripciones), el desplegable deberá mostrar la concatenación de las relaciones utilizadas (ejemplo: _Personas-Inscripciones + Inscripciones-Eventos_).


![Image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/f0489009-b23a-46e5-90a2-ec99321e25d1)

**Comment by jortilles** [comment]
Tras una primera revisión hemos llegado a la propuesta que:

Si hay relación directa. Mostrar sólo los caminos de la relación directa ( por todos los campos posibles).
Si no hay relación directa, mostramos todos los caminos posibles entre los módulos presentes en la consulta y el usuario filtra. 

Las relaciones se deben ordenar por source_table y source_column alfabeticamente para garantizar que  stic_payment_commitments_accountsaccounts_ida esté antes que stic_payment_commitments_accounts**_1**accounts_ida

**Comment by jortilles** [comment]
![image](https://github.com/SinergiaTIC/SinergiaDA/assets/1340212/0133c01a-370f-4426-822f-d3cdae1f0480)

**Comment by jortilles** [comment]
Creado PR https://github.com/SinergiaTIC/SinergiaDA/pull/140
