### ISSUE TITLE
Incidencia - EDA - Filtros de fecha fallan en los cambios de mes

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#54]
Cuando en un filtro de fecha (contrastado en un campo "Fecha/Hora", pero diría que idéntico en campos "Fecha" al aplicar el filtro "Toda la semana" en un informe (de lunes a domingo) deja de funcionar correctamente cuando en esa semana existe un cambio de mes y pasa a coger la semana de lunes a domingo... y el resto del mes siguiente.

A modo de ejemplo (siendo fecha uno de octubre):

![image](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/52454981/ff56607f-f6e3-4c4f-9a6a-f7eed83a4147)

El resultado del filtro es:

![image](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/52454981/10ea2a94-e49d-4fb0-a478-e4824140b07f)

**NOTA: ES MUY PROBABLE QUE ESTE ERROR SE PRODUZCA EN LOS DÍAS DEL MES ENTRANTE (es decir, el día 30 de septiembre no daba ese error, pero sí el 1 de octubre).** Bug no fácil de reproducir, pero aprovechando su detección quería dejarlo reflejado en este issue... puede modificar cada mes un conjunto de informes que se basen en actividades semanales - seguimientos, intervenciones, citas, etc -; a revisar el código que determina el alcance de esa "semana actual".

ADICIONALMENTE (a decidir si deben abrirse tantos issues como errores o serviría con revisar y resolver éste); cuando con este contexto (1 de octubre, inicio de mes en medio de una semana):

- al marcar "Este mes" selecciona únicamente el 1 de octubre (cuando intuitivamente debería hacerlo con todo el mes de octubre) - quizá se trata de cambiar etiqueta a "Este mes hasta hoy", aunque no sé si tiene sentido
- pero al marcar "El mes pasado" selecciona únicamente el 1 de septiembre; aquí sí que la idea de "El mes pasado hasta el mismo día en el que estamos hoy" no sé si tiene sentido
Nota: "toda la semana pasada" y "todo el mes pasado" no deberían existir si existen "la semana pasada" y "el mes pasado" si consideramos que cuando haces esa selección es para verlos completos.

- este año es "este año hasta hoy", cuando intuitivamente parece selección de 1/1 a 31/12... y, además, no existe el "Todo este año" que parecería necesario para seguir con el mismo criterio que los anteriores
- el de año anterior lleva hasta el mismo día de hoy pero en el año pasado...

EN RESUMEN: creo que, más allá del error de "toda esta semana" en los cambios de mes, deberían revisarse etiquetas y alcance de los filtros "textuales" (quizá, aprovechando, reemplazar lo de los "n días" que aparecen por "n meses" o "n trimestres", pero es otra cuestión.

**Comment by juanSTIC** [comment]
El uso de la librería moment.js permite extraer directamente el objeto fecha del primer y último día de la semana sin tener que mirar si el día actual es domingo o lunes..., hemos incluido una propuesta que creemos que es más correcta en base al ISO 8601 que establece el lunes como primer día de la semana en todos los casos. La hemos incluido en el PR.
En caso de no estar de acuerdo, por favor, incluir la propuesta que hay en este mismo issue en el Pull Request para su validación.

**Comment by asafJortilles** [comment]
@juanSTIC @PaulaaSTIC @jortilles 
Por mi parte está probado y funciona correctamente con esta última propuesta.
