### ISSUE TITLE
Incidencia - EDA - No funciona el filtro de valores no nulos dentro de un campo en un panel

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#56]
Dentro de un panel, se incluye un filtro en un campo, de forma que no se muestren valores nulos. Sin embargo, al ejecutar el panel, se siguen mostrando valores nulos. 
<img width="437" alt="image" src="https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/126673923/9470dd76-a187-456c-b38b-f15f996c69db">

**Comment by juanSTIC** [comment]
Se ha visto que el problema se produce por que la combinación de los siguientes fltros no funciona:



![Image](https://github.com/SinergiaTIC/SinergiaDA/assets/46187267/c1b4dadb-ad56-4ad2-af65-0d48801b58a4)


Cuando se elige esta combinación, EDA añade una clausula Where con las dos condiciones separadas por un `OR` lo que hace que no funcione correctamente, debería funcionar con un `AND`

`where  (sda_l_contacts_stic_gender_c_stic_genders_list.value  <> ''  
  or sda_l_contacts_stic_gender_c_stic_genders_list.value is not null 
  )  `

**Comment by jortilles** [comment]
Se crea https://github.com/SinergiaTIC/SinergiaDA/pull/99/

**Comment by PaulaaSTIC** [comment]
Resuelto en: https://github.com/SinergiaTIC/SinergiaDA/pull/153
