### ISSUE TITLE
Incidencia - EDA - Error en la visualización de etiquetas en gráficos de barras según ordenamiento

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#58]
### Descripción
Los gráficos de barras presentan un comportamiento inconsistente al mostrar o no las etiquetas, dependiendo de si los valores están ordenados al generar el panel.
![image_720](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/46187267/de54491c-22aa-4855-a091-a1f3a84c7be2)
![image_720](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/46187267/b809b53c-a329-4107-a94d-84185c15b5d0)

### Cómo reproducirlo
1. Crear o abrir un panel con un gráfico de barras.
2. Observar que las etiquetas se muestran o no dependiendo de si los valores están ordenados.

### Solución propuesta
Revisar y corregir la lógica de visualización de etiquetas en los gráficos de barras para asegurar que se muestren consistentemente, independientemente del ordenamiento de los valores.

**Comment by jortilles** [comment]
@asafJortilles  Revisar nulos

**Comment by jortilles** [comment]
Se arregla con el pr https://github.com/SinergiaTIC/SinergiaDA/pull/105

**Comment by PaulaaSTIC** [comment]
Resuelto en: https://github.com/SinergiaTIC/SinergiaDA/pull/153
