### ISSUE TITLE
Mejora - EDA - Habilitar filtros no editables/no visibles a nivel de informe

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#59]
**Es una de las propuestas de modificación más importantes, a mi entender.** 
Poder indicar en los filtros de informes que son "no editables" o directamente que queden ocultos si no eres administrador/a.
Si pretendes un informe para una zona geográfica concreta, o para un proyecto... tienes que aplicar un filtro de informe - con alcance a todos los paneles, por ejemplo -. Cualquier persona con acceso al informe puede modificar dicho filtro y, en ese momento, quizá algunos elementos pierden su sentido - colores en KPIs según límites, aparición de categorías que no debían aparecer, comentarios sobre valores base que podrían hacer referencia al filtro inicial, ...

Quizá al crear el filtro (no olvidemos que lo puede hacer quien "administra" el informe), se puede marcar de alguna forma para que sea visible pero no editable - así informa de la existencia del mismo -.

La opción es filtros "panel a panel", lo cuál resulta extremadamente farragoso.

En este ejemplo, queremos un informe para registros activos... pero cualquiera puede incorporar los que no lo están (y aparecerían relaciones que ya no queremos gestionar, por ejemplo).
![image](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/52454981/930214bf-c47c-47b7-8337-628937ff50b1)

**Comment by asafJortilles** [comment]
@juanSTIC  No editables y no visibles son cosas distintas. 

No editable quiere decir que veo que hay un filltro pero que no lo puedo tocar.



![Image](https://github.com/SinergiaTIC/SinergiaDA/assets/122270752/9b56c7f2-c047-44bc-87b4-f1556b3eec05)



No visible quiere decir que hay un filtro. Pero que yo no soy consciente de el porque no me aparece.   Si por ejemplo sólo hay uno y es no visible se verá de la siguente forma





La única forma de saber si tienes un filtro o varios es accediendo a la definición de la consulta. y tampoco podrás llegar a ver los valores seleccionados. 



![Image](https://github.com/SinergiaTIC/SinergiaDA/assets/122270752/013b3b2e-b27f-4143-bfd6-8f499c4e6adb)


Por lo que la experiencia de usuario es muy distinta. No editable es que me estan filtrando por algo. No visible es que no soy conscinete de que me filtran.

**Comment by juanSTIC** [comment]
Diría que el mejor de los escenarios posible es poder elegir cualquiera de las tres posibles opciones:
- Normal: Como funciona ahora
- Solo lectura (readOnly): que me permita ver los filtros aplicados, pero que no pueda interactuar con ellos.
- Oculto (hidden): no veo los filtros aplicados ni puedo interactuar de ningún modo.

Si es razonablemente sencillo habilitaría las tres opciones.

Añadiría que, en el caso de los filtros de ocultos, el botón _Filtrar_ también debería ocultarse, y en el caso del modo solo lectura, el boton debería estar desactivado, o ser susutituido por un texto como _Filtros aplicados_ o similar.

**Comment by jortilles** [comment]
Si... los valores posibles son "Normal", "Deshabilitado" y "Oculto"

**Comment by asafJortilles** [comment]
Qué tratamiento le damos a los filtros si hay alguno público y otros readOnly? los pongo todos en readOnly ?

**Comment by juanSTIC** [comment]
> Qué tratamiento le damos al botón de filtrado si hay alguno público y otros readOnly?

El botón filtrar SOLO debe aparecer si hay algún filtro público (normal) y debe funcionar igual que ahora.

**Comment by asafJortilles** [comment]
Hola Juan. Creo que esto lo resolvimos de inmediato, en una conversación previa. 
Si lo has probado en la rama SDA#59 y crees que el funcionamiento es el adecuado, está listo para PR. 
Se lo paso a @jortilles para validación.

**Comment by jortilles** [comment]
Se cdrea pr https://github.com/SinergiaTIC/SinergiaDA/pull/97

**Comment by juanSTIC** [comment]
Mergeado
