### ISSUE TITLE
Incidencia - EDA - No se puede modificar el orden de los atributos en el panel

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#60]
## Descripción

No es posible reordenar los atributos en el panel una vez que han sido añadidos. Incluso al llegar al límite de la primera fila de atributos, no se pueden colocar los siguientes de forma ordenada según las preferencias del usuario. La única opción para gestionar un gran número de atributos es mediante doble clic en la variable para agregarla secuencialmente, pero no se pueden realizar cambios en el orden posteriormente. Se necesita una solución para permitir la reordenación de atributos en el panel después de su inclusión.

![image](https://github.com/SinergiaTIC/Sinergia-Data-Analytics/assets/46187267/18e5ea98-3978-4f80-9a00-214f8805ba9e)

**Comment by juanSTIC** [comment]
Duplicado
