### ISSUE TITLE
Incidencia - APP - Protección de usuarios necesarios para SinergiaDA

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaDA#91]
### Descripción

Algunos usuarios en SinergiaDA son considerados esenciales para el funcionamiento del sistema y son necesarios para ciertas funcionalidades, como los informes públicos. Sin embargo, actualmente estos usuarios pueden ser eliminados fácilmente por un administrador a través de la interfaz de gestión de usuarios de EDA. 

Se sugiere implementar una protección para estos usuarios, evitando su eliminación a través de la interfaz. Una solución propuesta es que estos usuarios se muestren atenuados y que no se ofrezca el menú contextual de acciones para ellos.

### Cómo reproducirlo

1. Iniciar sesión en SinergiaDA como usuario administrador.
2. Navegar a la interfaz de gestión de usuarios de EDA.
3. Intentar eliminar los usuarios `edaanonim@jortilles.com` y `eda@sinergiada.org`.

### Notas adicionales

Se debe asegurar que los cambios no afecten la capacidad de gestión de otros usuarios que no son considerados de sistema. Además, es importante considerar la retrocompatibilidad con las versiones existentes de SinergiaDA y EDA.

**Comment by jortilles** [comment]
@asafJortilles  Cuando se borra un usuario hay que comprobar que no sea uno de los del sistema.
Lo mismo aplica para los roles.

**Comment by asafJortilles** [comment]
@jortilles rama SDA#91

**Comment by jortilles** [comment]
Se crea el PR https://github.com/SinergiaTIC/SinergiaDA/pull/112
